/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YrSLeUt5nEn
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { RenderOtps } from "./otp";
import { PlusIcon } from "./icons/PlusIcon";
import { Modal, modalHandler } from "./ui/Modal";
import { Form } from "./form";

export function Component() {
  return (
    <div className="max-w-md mx-auto p-6 bg-background rounded-lg shadow-lg min-width">
      <Modal />
      <header className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">2FA Authenticator</h1>
      </header>
      <div className="space-y-4">
        <RenderOtps />
      </div>

      <Button
        className="mt-6 w-full"
        onClick={() =>
          modalHandler.open({
            body: <Form />,
          })
        }
      >
        <PlusIcon className="h-4 w-4 mr-2" />
        Add OTP
      </Button>
    </div>
  );
}
